# Generated by Django 3.0.3 on 2020-04-01 15:06

import data_api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('listenNotesId', models.CharField(blank=True, max_length=256)),
                ('link', models.URLField(blank=True, null=True)),
                ('audio', models.URLField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pub_date_ms', models.DateTimeField(blank=True, default=None, null=True)),
                ('audio_length_sec', models.IntegerField(blank=True, default=0, null=True)),
                ('explicit_content', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('listenNotesId', models.CharField(blank=True, max_length=256)),
                ('type', models.CharField(max_length=256)),
                ('editor', models.CharField(max_length=256)),
                ('thumbnail', models.URLField(blank=True)),
                ('podcastPicture', models.ImageField(blank=True, upload_to=data_api.models.scramble_uploaded_filename)),
                ('durationMax', models.IntegerField(blank=True)),
                ('durationMin', models.IntegerField(blank=True)),
                ('about', models.TextField()),
                ('public', models.CharField(max_length=256)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=256)),
                ('Type', models.CharField(max_length=256)),
                ('profilePicture', models.ImageField(blank=True, upload_to=data_api.models.scramble_uploaded_filename)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PodcastStatGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plays', models.IntegerField()),
                ('nbEpisodes', models.IntegerField()),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Podcast')),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('updateDate', models.DateField(auto_now_add=True)),
                ('plays', models.IntegerField()),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Episode')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Podcast'),
        ),
        migrations.CreateModel(
            name='Compaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('startDate', models.DateField(auto_now=True)),
                ('compaignPicture', models.ImageField(blank=True, upload_to=data_api.models.scramble_uploaded_filename)),
                ('announcer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=256)),
                ('startDate', models.DateField(auto_now=True)),
                ('status', models.CharField(max_length=256)),
                ('Requesttext', models.TextField()),
                ('compaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Compaign')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Podcast')),
            ],
        ),
    ]
