# Generated by Django 3.0.3 on 2020-04-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0003_auto_20200401_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
