# Generated by Django 3.0.3 on 2020-04-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0006_auto_20200401_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='durationMax',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='durationMin',
        ),
    ]
