# Generated by Django 3.0.3 on 2020-04-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0007_auto_20200402_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='type',
            new_name='genre',
        ),
    ]
