# Generated by Django 3.0.3 on 2020-04-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0008_auto_20200405_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
