# Generated by Django 3.0.3 on 2020-05-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0012_episode_nb_episodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='nb_episodes',
        ),
        migrations.AddField(
            model_name='podcast',
            name='nb_episodes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
